version: '3.9'

services:

  redmine:
    image: redmine
    container_name: myredmine
    restart: always
    volumes:
      - ./data/redmine:/usr/src/redmine/files
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
     
  db:
    image: mysql:5.6
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine